### ISSUE TITLE
recovring info from .seco ?

### ISSUE THREAD

**Issue by KobraIQ** [ExodusMovement/seco-file#14]
Hi I forgot my exodus wallet password and info and i have all info backed up but it's all encrypted Files like "seed.seco" and "two-factor.seco" "info.seco" and the "passphrase.json" and i stumbled upon this  and dont know how to use this "https://github.com/ExodusMovement/seco-file" any help ??

![him2](https://github.com/ExodusMovement/seco-file/assets/112991571/96695906-5ba0-4700-ac8c-2bf803e3377a)

**Comment by RyanZim** [comment]
Please contact support@exodus.com for assistance
